project:
  type: website

website:
  title: "FRW Abschlusstraining"
  navbar:
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-line-numbers: true
  pdf:
    pdf-engine: lualatex
    pdf-engine-opts:
      - -shell-escape
    fontsize: 11pt
    documentclass: scrartcl
    classoption: a4paper
    toc: false
    include-in-header: preamble.tex
    code-line-numbers: true 
    mainfont: "TeX Gyre Termes"
    monofont: "TeX Gyre Cursor"